finished BY RYANISYYDS
milkteamc/wiki pull request #4
Opened 2023-11-04 09:52 UTC by RyanisyydsTT

2023-11-04 10:02 UTC, MagicTeaMC requested changes
檢查完成了，請更改我所提到的問題 謝謝~

2023-11-04 10:02 UTC, MagicTeaMC commented on daily.md
> +- `/signin click` - 補簽。格式: `/signin click 2023-11-29 (年-月-日)`。
(年-月-日) 不應該包含在 ` 中

2023-11-04 10:02 UTC, MagicTeaMC commented on daily.md
> +![image](https://github.com/RyanisyydsTT/wiki/assets/129717677/c040a3cd-e77a-4378-a559-67bd92c99c73)
same

2023-11-04 10:02 UTC, MagicTeaMC commented on guild.md
> +- `/guild create` - 建立工會指令。使用方法: `/guild create 公會名稱`。
[公會名稱] 才對

2023-11-04 10:02 UTC, MagicTeaMC commented on pvp.md
> +- `/pvp off` 關閉PVP
PVP 應該不只這些吧

2023-11-04 10:02 UTC, MagicTeaMC commented on season.md
> +好短..............
hmm 又變成心得了

2023-11-04 12:48 UTC, RyanisyydsTT commented
fixed?

2023-11-04 12:48 UTC, MagicTeaMC commented on chestshop.md
> +**箱子商店**
here

2023-11-04 12:49 UTC, MagicTeaMC commented on daily.md
> +**簽到系統 (玩家可使用指令的列表)**
這邊也要使用標題

2023-11-04 12:49 UTC, MagicTeaMC commented on guild.md
> +**公會系統 (常用功能)**
same

2023-11-04 12:50 UTC, MagicTeaMC commented on land.md
> +- `/land trust 玩家名稱` - 授予特定玩家在你土地上的信任。
[玩家名稱] 才對 下方的也是

2023-11-04 12:52 UTC, MagicTeaMC commented on chestshop.md
> +3. 按下 "Enter"，正常情况下，箱子会出现一个告示牌，但目前顯示為 "無庫存狀態"。
簡體?

2023-11-04 13:49 UTC, MagicTeaMC requested changes

2023-11-04 13:49 UTC, MagicTeaMC commented on [].md
> +# [ ]功能
要給他個名稱 例如聊天欄功能

2023-11-04 13:53 UTC, MagicTeaMC commented on README.md
> +## DC連動
Discord*

2023-11-04 14:02 UTC, MagicTeaMC requested changes
剛剛漏看了幾個 這次改完應該就沒什麼問題了！謝謝

2023-11-04 14:02 UTC, MagicTeaMC commented on chestshop.md
> +3. 按下 "Enter"，正常情况下，箱子会出现一个告示牌，但目前顯示為 "無庫存狀態"。
here

2023-11-04 14:02 UTC, MagicTeaMC commented on daily.md
> +**簽到系統 (玩家可使用指令的列表)**
here

2023-11-04 14:02 UTC, MagicTeaMC commented on guild.md
> +**公會系統 (常用功能)**
here

2023-11-04 14:02 UTC, MagicTeaMC commented on land.md
> +- `/land trust 玩家名稱` - 授予特定玩家在你土地上的信任。
here

2023-11-04 14:40 UTC, MagicTeaMC requested changes

2023-11-04 14:40 UTC, MagicTeaMC commented on README.md
> +## Discord連動
這些也要加入目錄中

2023-11-06 08:54 UTC, MagicTeaMC approved these changes
I will merge this PR later, thanks for ur hark works!

2023-11-16 13:21 UTC, merged